name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SECRET }}
          script: |
            cd /var/www/Laravel-web-task-tracker

            cat > .env << 'EOF'
            APP_NAME=Laravel
            APP_ENV=production
            APP_KEY=
            APP_DEBUG=false
            APP_URL=http://${{ secrets.EC2_HOST }}
            
            DB_CONNECTION=mysql
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=3306
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOF

            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan key:generate --force
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
